# Generated by Django 6.1 on 2026-09-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('cupos_disponibles', models.IntegerField()),
                ('estado', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('INVALIDO', 'Dato inválido')], max_length=10)),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'préstamo de notebook',
                'verbose_name_plural': 'préstamos de notebooks',
            },
        ),
    ]
